Cymax-DCBackend/Models/ProductsReviewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Cymax_DCBackend.Models
{
    public class ProductsReviewModels
    {
        [Display(Name = "Product ID")]
        public string productID { get; set; }

        [Required]
        [Display(Name = "From")]
        public DateTime From { get; set; }

        [Required]
        [Display(Name = "To")]
        public DateTime To { get; set; }
    }
}

Cymax-DCBackend/Controllers/BackendController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Data.OleDb;
using Cymax_DCBackend.Models;
using System.Web.Security;

namespace Cymax_DCBackend.Controllers
{
    public class BackendController : Controller
    {

        static string ConnectionString = ConfigurationManager.ConnectionStrings["CymaxConnection"].ConnectionString;
        static int ClientId = int.Parse(ConfigurationManager.AppSettings["ClientID"]);

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Products()
        {
            ViewBag.Title = "Products";

            return View();
        }

        public ActionResult ImportProducts()
        {
            ViewBag.Title = "Import Products";

            if (Session["AuthState"] != "Authenticated")
            {
                return RedirectToAction("Login", "User");
            }
            else
            {
                return View();
            }
        }

        public ActionResult ImportAttributes()
        {
            ViewBag.Title = "Import Attributes";

            if (Session["AuthState"] != "Authenticated")
            {
                return RedirectToAction("Login", "User");
            }
            else
            {
                return View();
            }
        }


        public ActionResult Attributes()
        {
            ViewBag.Title = "Attributes";

            return View();
        }

        public ActionResult dbProductsUpdate(string filePath)
        {

            DataTable sheetData = new DataTable();
            using (OleDbConnection conn = new OleDbConnection("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + filePath + ";Extended Properties='Excel 8.0;HDR={1}'"))
            {

                //Get the name of First Sheet
                conn.Open();
                DataTable dtExcelSchema;
                dtExcelSchema = conn.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                string SheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();

                // retrieve the data using data adapter
                OleDbDataAdapter sheetAdapter = new OleDbDataAdapter("select 1 as ClientID, * from [" + SheetName + "]", conn);
                sheetAdapter.Fill(sheetData);
            }

            string consString = ConfigurationManager.ConnectionStrings["CymaxConnection"].ConnectionString;
            using (SqlConnection con = new SqlConnection(consString))
            {
                using (SqlBulkCopy sqlBulkCopy = new SqlBulkCopy(con))
                {
                    //Set the database table name
                    sqlBulkCopy.ColumnMappings.Add("ClientID", "ClientID");
                    sqlBulkCopy.ColumnMappings.Add("Data ID", "ProductID");
                    sqlBulkCopy.ColumnMappings.Add("Product Name", "Name");
                    sqlBulkCopy.ColumnMappings.Add("Category", "Category");
                    sqlBulkCopy.ColumnMappings.Add("Product Description", "Description");
                    sqlBulkCopy.ColumnMappings.Add("Product URL", "Url");
                    sqlBulkCopy.ColumnMappings.Add("Image URL (Main)", "ImageUrl");
                    //sqlBulkCopy.ColumnMappings.Add("Image URL (Extra 1)", "ImageUrl2");
                    sqlBulkCopy.DestinationTableName = "dbo.Products";
                    con.Open();
                    sqlBulkCopy.WriteToServer(sheetData);
                    con.Close();
                }
            }

            return View("Products");
        }

        public ActionResult dbAttributesUpdate(string filePath)
        {
            DataTable sheetData = new DataTable();
            using (OleDbConnection conn = new OleDbConnection("Provider=Microsoft.ACE.OLEDB.12.0;Data Source=" + filePath + ";Extended Properties='Excel 8.0;HDR={1}'"))
            {

                //Get the name of First Sheet
                conn.Open();
                DataTable dtExcelSchema;
                dtExcelSchema = conn.GetOleDbSchemaTable(OleDbSchemaGuid.Tables, null);
                string SheetName = dtExcelSchema.Rows[0]["TABLE_NAME"].ToString();
                conn.Close();

                conn.Open();
                // retrieve the data using data adapter
                OleDbDataAdapter sheetAdapter = new OleDbDataAdapter("select 1 as ClientID, * from [" + SheetName + "]", conn);
                sheetAdapter.Fill(sheetData);
            }

            string consString = ConfigurationManager.ConnectionStrings["CymaxConnection"].ConnectionString;
            using (SqlConnection con = new SqlConnection(consString))
            {
                using (SqlBulkCopy sqlBulkCopy = new SqlBulkCopy(con))
                {
                    //Set the database table name
                    sqlBulkCopy.ColumnMappings.Add("ClientID", "ClientID");
                    sqlBulkCopy.ColumnMappings.Add("Category", "Category");
                    sqlBulkCopy.ColumnMappings.Add("Attribute Group", "AttributeGroup");
                    sqlBulkCopy.ColumnMappings.Add("Attribute", "Attribute");
                    sqlBulkCopy.ColumnMappings.Add("Parent Category", "ParentCategory");
                    sqlBulkCopy.DestinationTableName = "Attributes";
                    con.Open();
                    sqlBulkCopy.WriteToServer(sheetData);
                    con.Close();
                }
            }

            return View("Products");
        }

        // file upload for the products
        [HttpPost]
        public ActionResult ImportProducts(HttpPostedFileBase file)
        {
            if (file != null)
            {
                // check if the file is an .xlsx file or an unknow MIME
                if (file.ContentType == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" || file.ContentType == "application/octet-stream")
                {
                    try
                    {
                        string fileName = "products_" + Guid.NewGuid().ToString("N");
                        string path = Path.Combine(Server.MapPath("~/App_Data"), fileName);
                        file.SaveAs(path);
                        ViewBag.Message = "File uploaded successfully";
                        dbProductsUpdate(path);
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                else
                    ViewBag.Message = "Only .xlsx files are accepted!";
            }
            else
                ViewBag.Message = "Select a file to upload";

            return View("ImportProducts");
        }

        // file upload for the attributes
        [HttpPost]
        public ActionResult ImportAttributes(HttpPostedFileBase file)
        {
            if (file != null)
            {
                // check if the file is an .xlsx file or an unknown MIME
                if (file.ContentType == "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" || file.ContentType == "application/octet-stream")
                {
                    try
                    {
                        string fileName = "attributes_" + Guid.NewGuid().ToString("N");
                        string path = Path.Combine(Server.MapPath("~/App_Data"), fileName);
                        file.SaveAs(path);
                        ViewBag.Message = "File uploaded successfully";
                        dbAttributesUpdate(path);
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Message = "ERROR:" + ex.Message.ToString();
                    }
                }
                else
                    ViewBag.Message = "Only .xlsx files are accepted!";
            }
            else
                ViewBag.Message = "Select a file to upload";

            return View("ImportAttributes");
        }

        public ActionResult ProductsReview(Models.ProductsReviewModels date)
        {
            if (Session["AuthState"] != "Authenticated")
            {
                return RedirectToAction("Login", "User");
            }
            else
            {
                getReviews();
                return View();
            }
        }

        public void getReviews()
        {
            List<ProductReviewData> prodData = new List<ProductReviewData>();

            string queryString = @"	SELECT  PR.[ProductID]
		                                   ,[Name]
		                                   ,[AttributeGroup]
		                                   ,[Attribute]
		                                   ,SUM(IIF([Added]=1, 1,0)) ADDED
		                                   ,SUM(IIF([Added]=0, 1,0)) REMOVED
	                                  FROM  [ProductsReview] PR
	                                  JOIN  [Products] P ON P.ProductID = PR.ProductID
                                     WHERE  PR.[ClientID] = @ClientID
                                  GROUP BY  PR.[ProductID]
		                                   ,P.[Name]
		                                   ,[AttributeGroup]
		                                   ,[Attribute]";

            using (SqlConnection connection = new SqlConnection(ConnectionString))
            using (SqlCommand command = new SqlCommand(queryString, connection))
            {
                command.Parameters.AddWithValue("@ClientID", ClientId);
                connection.Open();
                SqlDataReader reader = command.ExecuteReader();

                if (reader.HasRows)
                {
                    while (reader.Read())
                    {
                        prodData.Add(new ProductReviewData
                        {
                            ProductId = reader.GetInt32(0),

Cymax-DCBackend/Views/Backend/Attributes.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.Title</h2>

<table style="width:100%;"><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr></table>

Cymax-DCBackend/Views/Backend/ImportAttributes.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("ImportAttributes", "Backend", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr>
            <td>
                <input type="file" name="file" />
            </td>
            <td>
                <input type="submit" value="Upload File" />
            </td>
        </tr>
    </table>
    <br /><br />
    @ViewBag.Message
}

Cymax-DCBackend/Views/Backend/ImportProducts.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.Title</h2>

@using (Html.BeginForm("ImportProducts", "Backend", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <table>
        <tr>
            <td>
                <input type="file" name="file" />
            </td>
            <td>
                <input type="submit" value="Upload File" />
            </td>
        </tr>
    </table>
    <br/><br/>
    @ViewBag.Message
}

Cymax-DCBackend/Views/Backend/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.Title</h2>

<div class="jumbotron">
    <h1>Cymax - Data cleansing backend</h1>
    <p class="lead">Provides support for the Android mobile application</p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Features</h2>
        <p>
            - Import xlsx of Attributes and Products into the database<br />
            - Control client requests through web-service<br />
            - Display products tags that were reviewed on the android app<br />
        </p>
    </div>
</div>

Cymax-DCBackend/Views/Backend/Products.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>@ViewBag.Title</h2>

<table style="width:100%;"><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr></table>

Cymax-DCBackend/Views/Backend/ProductsReview.cshtml
@Model
@{
    ViewBag.Title = "Products reviewed tags";
    ViewBag.Message = "Show tags added to products using the Cymax - Data Cleansing app";
    List<Cymax_DCBackend.Models.ProductReviewData> items = ViewBag.ProductReviews;
    @section scripts {
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
        <link rel="stylesheet" href="/resources/demos/style.css">
        <script>
            $(function () {
                $("#from").datepicker({
                    defaultDate: "+1w",
                    dateFormat: "yy-mm-dd",
                    changeMonth: true,
                    numberOfMonths: 3,
                    onClose: function (selectedDate) {
                        $("#to").datepicker("option", "minDate", selectedDate);
                    }
                });
                $("#to").datepicker({
                    defaultDate: "+1w",
                    changeMonth: true,
                    numberOfMonths: 3,
                    dateFormat: "yy-mm-dd",
                    onClose: function (selectedDate) {
                        $("#from").datepicker("option", "maxDate", selectedDate);
                    }
                });
            });
        </script>
    }

}
<h2>@ViewBag.Title</h2>
<h4>@ViewBag.Message</h4>

<section id="sectionIndexes">
    <article>
        @model Cymax_DCBackend.Models.ProductsReviewModels
        @using (Html.BeginForm("Search", "Backend", FormMethod.Post))
        {
            <!--
                <label for="productID">Product ID</label>
                <input type="text" id="productID" />
            -->
            <label for="from">From</label>
            <input type="text" id="from" name="from" value="@ViewBag.DateFrom">
            <label for="to">to</label>
            <input type="text" id="to" name="to" value="@ViewBag.DateTo">
            <input type="submit" value="Search"/>
        }

        <table style="width:100%;">
            <tr>
                <th>Product Id</th>
                <th>Attribute Group</th>
                <th>Attribute</th>
                <th>Total Added</th>
                <th>Total Removed</th>
            </tr>
            @foreach (var groupItem in ViewBag.GroupedProducts)
            {
                <tr>
                    <td>@groupItem.ProductId</td>
                    <td>@groupItem.Name</td>
                </tr>
                foreach (string attributeGroup in items.Where(x => x.ProductId == groupItem.ProductId).GroupBy(p => p.AttributeGroup).Select(y => y.Key).ToList<string>())
                {
                    <tr>
                        <td></td>
                        <td>@attributeGroup</td>
                    </tr>
                    foreach (Cymax_DCBackend.Models.ProductReviewData item in ((List<Cymax_DCBackend.Models.ProductReviewData>)ViewBag.ProductReviews).Where(p => p.ProductId == groupItem.ProductId && p.AttributeGroup == attributeGroup))
                    {
                        <tr>
                            <td></td>
                            <td></td>
                            <td>@item.Attribute</td>
                            <td>@item.Added</td>
                            <td>@item.Removed</td>
                        </tr>
                    }
                }
            }
        </table>
        <footer style="float:right;"></footer>
    </article>
</section>

Cymax-DCBackend/Views/Backend/Search.cshtml
@Model
@{
    ViewBag.Title = "Products reviewed tags";
    ViewBag.Message = "Show tags added to products using the Cymax - Data Cleansing app";
    List<Cymax_DCBackend.Models.ProductReviewData> items = ViewBag.ProductReviews;
    @section scripts {
        <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
        <script src="//code.jquery.com/jquery-1.10.2.js"></script>
        <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
        <link rel="stylesheet" href="/resources/demos/style.css">
        <script>
            $(function () {
                $("#from").datepicker({
                    defaultDate: "+1w",
                    changeMonth: true,
                    numberOfMonths: 3,
                    onClose: function (selectedDate) {
                        $("#to").datepicker("option", "minDate", selectedDate);
                    }
                });
                $("#to").datepicker({
                    defaultDate: "+1w",
                    changeMonth: true,
                    numberOfMonths: 3,
                    onClose: function (selectedDate) {
                        $("#from").datepicker("option", "maxDate", selectedDate);
                    }
                });
            });
        </script>
    }

}
<h2>@ViewBag.Title</h2>
<h4>@ViewBag.Message</h4>

<section id="sectionIndexes">
    <article>
        @model Cymax_DCBackend.Models.ProductsReviewModels
        @using (Html.BeginForm("Search", "Backend", FormMethod.Post))
        {
            <!--
                <label for="productID">Product ID</label>
                <input type="text" id="productID" />
            -->
            <label for="from">From</label>
            <input type="text" id="from" name="from">
            <label for="to">to</label>
            <input type="text" id="to" name="to">
            <input type="submit" value="Search" />
        }

        <table style="width:100%;">
            <tr>
                <th>Product Id</th>
                <th>Attribute Group</th>
                <th>Attribute</th>
                <th>Total Added</th>
                <th>Total Removed</th>
            </tr>
            @foreach (var groupItem in ViewBag.GroupedProducts)
            {
                <tr>
                    <td>@groupItem.ProductId</td>
                    <td>@groupItem.Name</td>
                </tr>
                foreach (string attributeGroup in items.Where(x => x.ProductId == groupItem.ProductId).GroupBy(p => p.AttributeGroup).Select(y => y.Key).ToList<string>())
                {
                    <tr>
                        <td></td>
                        <td>@attributeGroup</td>
                    </tr>
                    foreach (Cymax_DCBackend.Models.ProductReviewData item in ((List<Cymax_DCBackend.Models.ProductReviewData>)ViewBag.ProductReviews).Where(p => p.ProductId == groupItem.ProductId && p.AttributeGroup == attributeGroup))
                    {
                        <tr>
                            <td></td>
                            <td></td>
                            <td>@item.Attribute</td>
                            <td>@item.Added</td>
                            <td>@item.Removed</td>
                        </tr>
                    }
                }
            }
        </table>
        <footer style="float:right;"></footer>
    </article>
</section>